{-# OPTIONS -Wall #-}
-- | Reexport module
module HsTri(

    module Blender,
    module ClosedOrCensus6,
    module Codec.Rga.Parser,
    module Codec.Rga.Writer,
    module ConcreteNormal,
    module ConcreteNormal.PreRenderable,
    module Data.AscTuples,
    module Data.FormalOps,
    module Data.Vector,
    module DisjointUnion,
    module DotUtil,
    module EdgeCentered,
    module EqvGraphs,
    module ExampleTriangulations,
    module FaceLattice,
    module HomogenousTuples,
    module HsTri.Console,
    module Latexable,
    module Numeric.AD.Vector,
    module PreRenderable,
    module PrettyUtil,
    module QuadCoordinates,
    module QuadCoordinates.CanonExt,
    module QuadCoordinates.Dense,
    module QuadCoordinates.MatchingEquations,
    module QuadCoordinates.SolSetConversion,
    module R3Immersions,
    module Simplicial.SimplicialComplex,
    module StandardCoordinates,
    module StandardCoordinates.Dense,
    module StandardCoordinates.MatchingEquations,
    module StandardCoordinates.SurfaceQueries,
    module THUtil,
    module Tetrahedron.INormalDisc,
    module Tetrahedron.NormalConstants,
    module Tetrahedron.NormalDisc,
    module Tikz.Gen,
    module Tikz.Preview,
    module TriArcGraph,
    module Triangulation.Class,
    module Triangulation.FacetGluing,
    module Triangulation.Random,
    module Triangulation.Transformations,
    module Triangulation.VertexLink,
    module TriangulationCxtObject,
    module VerboseDD,

    ) where


import Blender
import ClosedOrCensus6
import Codec.Rga.Parser
import Codec.Rga.Writer
import ConcreteNormal
import ConcreteNormal.PreRenderable
import Data.AscTuples
import Data.FormalOps
import Data.Vector(Vector)
import DisjointUnion
import DotUtil(viewDot)
import EdgeCentered
import EqvGraphs
import ExampleTriangulations
import FaceLattice
import HomogenousTuples
import HsTri.Console
import Latexable
import Numeric.AD.Vector
import PreRenderable
import PrettyUtil
import QuadCoordinates
import QuadCoordinates.CanonExt
import QuadCoordinates.Dense
import QuadCoordinates.MatchingEquations
import QuadCoordinates.SolSetConversion
import R3Immersions
import Simplicial.SimplicialComplex
import StandardCoordinates
import StandardCoordinates.Dense
import StandardCoordinates.MatchingEquations
import StandardCoordinates.SurfaceQueries
import THUtil
import Tetrahedron.INormalDisc
import Tetrahedron.NormalConstants
import Tetrahedron.NormalDisc
import Tikz.Gen
import Tikz.Preview
import TriArcGraph
import Triangulation.Class
import Triangulation.FacetGluing
import Triangulation.Random
import Triangulation.Transformations
import Triangulation.VertexLink
import TriangulationCxtObject
import VerboseDD
