{-# OPTIONS -Wall #-}
-- | Reexport module
module HsTri(

    module Blender,
    module ClosedOrCensus6,
    module Codec.Rga.Writer,
    module ConcreteNormal.PreRenderable,
    module Data.AscTuples,
    module Data.FormalOps,
    module Data.Vect.Double.Base,
    module DisjointUnion,
    module DotUtil,
    module Either1,
    module EqvGraphs,
    module ExampleTriangulations,
    module FaceLattice,
    module HomogenousTuples,
    module Tetrahedron.INormalDisc,
    module Latexable,
    module PreRenderable,
    module PrettyUtil,
    module QuadCoordinates,
    module QuadCoordinates.CanonExt,
    module QuadCoordinates.Dense,
    module QuadCoordinates.MatchingEquations,
    module Simplicial.SimplicialComplex,
    module StandardCoordinates,
    module StandardCoordinates.Dense,
    module StandardCoordinates.MatchingEquations,
    module StandardCoordinates.SurfaceQueries,
    module THUtil,
    module Tetrahedron.NormalConstants,
    module Tetrahedron.NormalDisc,
    module Tikz.Gen,
    module Tikz.Preview,
    module TriArcGraph,
    module Triangulation.Class,
    module Triangulation.Random,
    module Triangulation.Transformations,
    module Triangulation.VertexLink,
    module TriangulationCxtObject,
    module VerboseDD,
    module HsTri.Console,
    module EdgeCentered,
    module Triangulation.FacetGluing

    ) where


import Blender
import ClosedOrCensus6
import Codec.Rga.Writer
import ConcreteNormal.PreRenderable
import Data.AscTuples
import Data.FormalOps
import Data.Vect.Double.Base(Vec3)
import DisjointUnion
import DotUtil(viewDot)
import Either1
import EqvGraphs
import ExampleTriangulations
import FaceLattice
import HomogenousTuples
import Tetrahedron.INormalDisc
import Latexable
import PreRenderable
import PrettyUtil
import QuadCoordinates
import QuadCoordinates.CanonExt
import QuadCoordinates.Dense
import QuadCoordinates.MatchingEquations
import Simplicial.SimplicialComplex
import StandardCoordinates
import StandardCoordinates.Dense
import StandardCoordinates.MatchingEquations
import StandardCoordinates.SurfaceQueries
import THUtil
import Tetrahedron.NormalConstants
import Tetrahedron.NormalDisc
import Tikz.Gen
import Tikz.Preview
import TriArcGraph
import Triangulation.Class
import Triangulation.Random
import Triangulation.Transformations
import Triangulation.VertexLink
import TriangulationCxtObject
import VerboseDD
import HsTri.Console
import EdgeCentered
import Triangulation.FacetGluing
